// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Arm-Debug/apap-cli/clients/go/authproto"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewAuthClient creates a new instance of AuthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthClient {
	mock := &AuthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthClient is an autogenerated mock type for the AuthClient type
type AuthClient struct {
	mock.Mock
}

type AuthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthClient) EXPECT() *AuthClient_Expecter {
	return &AuthClient_Expecter{mock: &_m.Mock}
}

// TargetLogin provides a mock function for the type AuthClient
func (_mock *AuthClient) TargetLogin(ctx context.Context, opts ...grpc.CallOption) (authproto.Auth_TargetLoginClient, error) {
	// grpc.CallOption
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for TargetLogin")
	}

	var r0 authproto.Auth_TargetLoginClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) (authproto.Auth_TargetLoginClient, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) authproto.Auth_TargetLoginClient); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(authproto.Auth_TargetLoginClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthClient_TargetLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TargetLogin'
type AuthClient_TargetLogin_Call struct {
	*mock.Call
}

// TargetLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...grpc.CallOption
func (_e *AuthClient_Expecter) TargetLogin(ctx any, opts ...any) *AuthClient_TargetLogin_Call {
	return &AuthClient_TargetLogin_Call{Call: _e.mock.On("TargetLogin",
		append([]any{ctx}, opts...)...)}
}

func (_c *AuthClient_TargetLogin_Call) Run(run func(ctx context.Context, opts ...grpc.CallOption)) *AuthClient_TargetLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *AuthClient_TargetLogin_Call) Return(auth_TargetLoginClient authproto.Auth_TargetLoginClient, err error) *AuthClient_TargetLogin_Call {
	_c.Call.Return(auth_TargetLoginClient, err)
	return _c
}

func (_c *AuthClient_TargetLogin_Call) RunAndReturn(run func(ctx context.Context, opts ...grpc.CallOption) (authproto.Auth_TargetLoginClient, error)) *AuthClient_TargetLogin_Call {
	_c.Call.Return(run)
	return _c
}
