// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Arm-Debug/apap-cli/clients/go/authproto"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc/metadata"
)

// NewAuthTargetLoginServer creates a new instance of AuthTargetLoginServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthTargetLoginServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthTargetLoginServer {
	mock := &AuthTargetLoginServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthTargetLoginServer is an autogenerated mock type for the Auth_TargetLoginServer type
type AuthTargetLoginServer struct {
	mock.Mock
}

type AuthTargetLoginServer_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthTargetLoginServer) EXPECT() *AuthTargetLoginServer_Expecter {
	return &AuthTargetLoginServer_Expecter{mock: &_m.Mock}
}

// Context provides a mock function for the type AuthTargetLoginServer
func (_mock *AuthTargetLoginServer) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// AuthTargetLoginServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type AuthTargetLoginServer_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *AuthTargetLoginServer_Expecter) Context() *AuthTargetLoginServer_Context_Call {
	return &AuthTargetLoginServer_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *AuthTargetLoginServer_Context_Call) Run(run func()) *AuthTargetLoginServer_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthTargetLoginServer_Context_Call) Return(context1 context.Context) *AuthTargetLoginServer_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *AuthTargetLoginServer_Context_Call) RunAndReturn(run func() context.Context) *AuthTargetLoginServer_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function for the type AuthTargetLoginServer
func (_mock *AuthTargetLoginServer) Recv() (*authproto.TargetLoginClientMessage, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *authproto.TargetLoginClientMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*authproto.TargetLoginClientMessage, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *authproto.TargetLoginClientMessage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authproto.TargetLoginClientMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthTargetLoginServer_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type AuthTargetLoginServer_Recv_Call struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *AuthTargetLoginServer_Expecter) Recv() *AuthTargetLoginServer_Recv_Call {
	return &AuthTargetLoginServer_Recv_Call{Call: _e.mock.On("Recv")}
}

func (_c *AuthTargetLoginServer_Recv_Call) Run(run func()) *AuthTargetLoginServer_Recv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AuthTargetLoginServer_Recv_Call) Return(targetLoginClientMessage *authproto.TargetLoginClientMessage, err error) *AuthTargetLoginServer_Recv_Call {
	_c.Call.Return(targetLoginClientMessage, err)
	return _c
}

func (_c *AuthTargetLoginServer_Recv_Call) RunAndReturn(run func() (*authproto.TargetLoginClientMessage, error)) *AuthTargetLoginServer_Recv_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function for the type AuthTargetLoginServer
func (_mock *AuthTargetLoginServer) RecvMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthTargetLoginServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type AuthTargetLoginServer_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *AuthTargetLoginServer_Expecter) RecvMsg(m any) *AuthTargetLoginServer_RecvMsg_Call {
	return &AuthTargetLoginServer_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *AuthTargetLoginServer_RecvMsg_Call) Run(run func(m any)) *AuthTargetLoginServer_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthTargetLoginServer_RecvMsg_Call) Return(err error) *AuthTargetLoginServer_RecvMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthTargetLoginServer_RecvMsg_Call) RunAndReturn(run func(m any) error) *AuthTargetLoginServer_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type AuthTargetLoginServer
func (_mock *AuthTargetLoginServer) Send(targetLoginServerMessage *authproto.TargetLoginServerMessage) error {
	ret := _mock.Called(targetLoginServerMessage)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*authproto.TargetLoginServerMessage) error); ok {
		r0 = returnFunc(targetLoginServerMessage)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthTargetLoginServer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type AuthTargetLoginServer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - targetLoginServerMessage *authproto.TargetLoginServerMessage
func (_e *AuthTargetLoginServer_Expecter) Send(targetLoginServerMessage any) *AuthTargetLoginServer_Send_Call {
	return &AuthTargetLoginServer_Send_Call{Call: _e.mock.On("Send", targetLoginServerMessage)}
}

func (_c *AuthTargetLoginServer_Send_Call) Run(run func(targetLoginServerMessage *authproto.TargetLoginServerMessage)) *AuthTargetLoginServer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *authproto.TargetLoginServerMessage
		if args[0] != nil {
			arg0 = args[0].(*authproto.TargetLoginServerMessage)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthTargetLoginServer_Send_Call) Return(err error) *AuthTargetLoginServer_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthTargetLoginServer_Send_Call) RunAndReturn(run func(targetLoginServerMessage *authproto.TargetLoginServerMessage) error) *AuthTargetLoginServer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function for the type AuthTargetLoginServer
func (_mock *AuthTargetLoginServer) SendHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthTargetLoginServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type AuthTargetLoginServer_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *AuthTargetLoginServer_Expecter) SendHeader(mD any) *AuthTargetLoginServer_SendHeader_Call {
	return &AuthTargetLoginServer_SendHeader_Call{Call: _e.mock.On("SendHeader", mD)}
}

func (_c *AuthTargetLoginServer_SendHeader_Call) Run(run func(mD metadata.MD)) *AuthTargetLoginServer_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthTargetLoginServer_SendHeader_Call) Return(err error) *AuthTargetLoginServer_SendHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthTargetLoginServer_SendHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *AuthTargetLoginServer_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function for the type AuthTargetLoginServer
func (_mock *AuthTargetLoginServer) SendMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthTargetLoginServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type AuthTargetLoginServer_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *AuthTargetLoginServer_Expecter) SendMsg(m any) *AuthTargetLoginServer_SendMsg_Call {
	return &AuthTargetLoginServer_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *AuthTargetLoginServer_SendMsg_Call) Run(run func(m any)) *AuthTargetLoginServer_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthTargetLoginServer_SendMsg_Call) Return(err error) *AuthTargetLoginServer_SendMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthTargetLoginServer_SendMsg_Call) RunAndReturn(run func(m any) error) *AuthTargetLoginServer_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function for the type AuthTargetLoginServer
func (_mock *AuthTargetLoginServer) SetHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthTargetLoginServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type AuthTargetLoginServer_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *AuthTargetLoginServer_Expecter) SetHeader(mD any) *AuthTargetLoginServer_SetHeader_Call {
	return &AuthTargetLoginServer_SetHeader_Call{Call: _e.mock.On("SetHeader", mD)}
}

func (_c *AuthTargetLoginServer_SetHeader_Call) Run(run func(mD metadata.MD)) *AuthTargetLoginServer_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthTargetLoginServer_SetHeader_Call) Return(err error) *AuthTargetLoginServer_SetHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthTargetLoginServer_SetHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *AuthTargetLoginServer_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function for the type AuthTargetLoginServer
func (_mock *AuthTargetLoginServer) SetTrailer(mD metadata.MD) {
	_mock.Called(mD)
	return
}

// AuthTargetLoginServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type AuthTargetLoginServer_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *AuthTargetLoginServer_Expecter) SetTrailer(mD any) *AuthTargetLoginServer_SetTrailer_Call {
	return &AuthTargetLoginServer_SetTrailer_Call{Call: _e.mock.On("SetTrailer", mD)}
}

func (_c *AuthTargetLoginServer_SetTrailer_Call) Run(run func(mD metadata.MD)) *AuthTargetLoginServer_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthTargetLoginServer_SetTrailer_Call) Return() *AuthTargetLoginServer_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthTargetLoginServer_SetTrailer_Call) RunAndReturn(run func(mD metadata.MD)) *AuthTargetLoginServer_SetTrailer_Call {
	_c.Run(run)
	return _c
}
