// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Arm-Debug/apap-cli/clients/go/tetherproto"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewTetherClient creates a new instance of TetherClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTetherClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TetherClient {
	mock := &TetherClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TetherClient is an autogenerated mock type for the TetherClient type
type TetherClient struct {
	mock.Mock
}

type TetherClient_Expecter struct {
	mock *mock.Mock
}

func (_m *TetherClient) EXPECT() *TetherClient_Expecter {
	return &TetherClient_Expecter{mock: &_m.Mock}
}

// Hold provides a mock function for the type TetherClient
func (_mock *TetherClient) Hold(ctx context.Context, opts ...grpc.CallOption) (tetherproto.Tether_HoldClient, error) {
	// grpc.CallOption
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Hold")
	}

	var r0 tetherproto.Tether_HoldClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) (tetherproto.Tether_HoldClient, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) tetherproto.Tether_HoldClient); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tetherproto.Tether_HoldClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TetherClient_Hold_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hold'
type TetherClient_Hold_Call struct {
	*mock.Call
}

// Hold is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...grpc.CallOption
func (_e *TetherClient_Expecter) Hold(ctx any, opts ...any) *TetherClient_Hold_Call {
	return &TetherClient_Hold_Call{Call: _e.mock.On("Hold",
		append([]any{ctx}, opts...)...)}
}

func (_c *TetherClient_Hold_Call) Run(run func(ctx context.Context, opts ...grpc.CallOption)) *TetherClient_Hold_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *TetherClient_Hold_Call) Return(tether_HoldClient tetherproto.Tether_HoldClient, err error) *TetherClient_Hold_Call {
	_c.Call.Return(tether_HoldClient, err)
	return _c
}

func (_c *TetherClient_Hold_Call) RunAndReturn(run func(ctx context.Context, opts ...grpc.CallOption) (tetherproto.Tether_HoldClient, error)) *TetherClient_Hold_Call {
	_c.Call.Return(run)
	return _c
}
