// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Arm-Debug/apap-cli/clients/go/tetherproto"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc/metadata"
)

// NewTetherHoldServer creates a new instance of TetherHoldServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTetherHoldServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TetherHoldServer {
	mock := &TetherHoldServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TetherHoldServer is an autogenerated mock type for the Tether_HoldServer type
type TetherHoldServer struct {
	mock.Mock
}

type TetherHoldServer_Expecter struct {
	mock *mock.Mock
}

func (_m *TetherHoldServer) EXPECT() *TetherHoldServer_Expecter {
	return &TetherHoldServer_Expecter{mock: &_m.Mock}
}

// Context provides a mock function for the type TetherHoldServer
func (_mock *TetherHoldServer) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// TetherHoldServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type TetherHoldServer_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *TetherHoldServer_Expecter) Context() *TetherHoldServer_Context_Call {
	return &TetherHoldServer_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *TetherHoldServer_Context_Call) Run(run func()) *TetherHoldServer_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TetherHoldServer_Context_Call) Return(context1 context.Context) *TetherHoldServer_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *TetherHoldServer_Context_Call) RunAndReturn(run func() context.Context) *TetherHoldServer_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function for the type TetherHoldServer
func (_mock *TetherHoldServer) Recv() (*tetherproto.PulseRequest, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *tetherproto.PulseRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*tetherproto.PulseRequest, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *tetherproto.PulseRequest); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tetherproto.PulseRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TetherHoldServer_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type TetherHoldServer_Recv_Call struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *TetherHoldServer_Expecter) Recv() *TetherHoldServer_Recv_Call {
	return &TetherHoldServer_Recv_Call{Call: _e.mock.On("Recv")}
}

func (_c *TetherHoldServer_Recv_Call) Run(run func()) *TetherHoldServer_Recv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TetherHoldServer_Recv_Call) Return(pulseRequest *tetherproto.PulseRequest, err error) *TetherHoldServer_Recv_Call {
	_c.Call.Return(pulseRequest, err)
	return _c
}

func (_c *TetherHoldServer_Recv_Call) RunAndReturn(run func() (*tetherproto.PulseRequest, error)) *TetherHoldServer_Recv_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function for the type TetherHoldServer
func (_mock *TetherHoldServer) RecvMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TetherHoldServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type TetherHoldServer_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *TetherHoldServer_Expecter) RecvMsg(m any) *TetherHoldServer_RecvMsg_Call {
	return &TetherHoldServer_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *TetherHoldServer_RecvMsg_Call) Run(run func(m any)) *TetherHoldServer_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TetherHoldServer_RecvMsg_Call) Return(err error) *TetherHoldServer_RecvMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TetherHoldServer_RecvMsg_Call) RunAndReturn(run func(m any) error) *TetherHoldServer_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type TetherHoldServer
func (_mock *TetherHoldServer) Send(pulseAck *tetherproto.PulseAck) error {
	ret := _mock.Called(pulseAck)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*tetherproto.PulseAck) error); ok {
		r0 = returnFunc(pulseAck)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TetherHoldServer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type TetherHoldServer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - pulseAck *tetherproto.PulseAck
func (_e *TetherHoldServer_Expecter) Send(pulseAck any) *TetherHoldServer_Send_Call {
	return &TetherHoldServer_Send_Call{Call: _e.mock.On("Send", pulseAck)}
}

func (_c *TetherHoldServer_Send_Call) Run(run func(pulseAck *tetherproto.PulseAck)) *TetherHoldServer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *tetherproto.PulseAck
		if args[0] != nil {
			arg0 = args[0].(*tetherproto.PulseAck)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TetherHoldServer_Send_Call) Return(err error) *TetherHoldServer_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TetherHoldServer_Send_Call) RunAndReturn(run func(pulseAck *tetherproto.PulseAck) error) *TetherHoldServer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function for the type TetherHoldServer
func (_mock *TetherHoldServer) SendHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TetherHoldServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type TetherHoldServer_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *TetherHoldServer_Expecter) SendHeader(mD any) *TetherHoldServer_SendHeader_Call {
	return &TetherHoldServer_SendHeader_Call{Call: _e.mock.On("SendHeader", mD)}
}

func (_c *TetherHoldServer_SendHeader_Call) Run(run func(mD metadata.MD)) *TetherHoldServer_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TetherHoldServer_SendHeader_Call) Return(err error) *TetherHoldServer_SendHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TetherHoldServer_SendHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *TetherHoldServer_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function for the type TetherHoldServer
func (_mock *TetherHoldServer) SendMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TetherHoldServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type TetherHoldServer_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *TetherHoldServer_Expecter) SendMsg(m any) *TetherHoldServer_SendMsg_Call {
	return &TetherHoldServer_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *TetherHoldServer_SendMsg_Call) Run(run func(m any)) *TetherHoldServer_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TetherHoldServer_SendMsg_Call) Return(err error) *TetherHoldServer_SendMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TetherHoldServer_SendMsg_Call) RunAndReturn(run func(m any) error) *TetherHoldServer_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function for the type TetherHoldServer
func (_mock *TetherHoldServer) SetHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TetherHoldServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type TetherHoldServer_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *TetherHoldServer_Expecter) SetHeader(mD any) *TetherHoldServer_SetHeader_Call {
	return &TetherHoldServer_SetHeader_Call{Call: _e.mock.On("SetHeader", mD)}
}

func (_c *TetherHoldServer_SetHeader_Call) Run(run func(mD metadata.MD)) *TetherHoldServer_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TetherHoldServer_SetHeader_Call) Return(err error) *TetherHoldServer_SetHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TetherHoldServer_SetHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *TetherHoldServer_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function for the type TetherHoldServer
func (_mock *TetherHoldServer) SetTrailer(mD metadata.MD) {
	_mock.Called(mD)
	return
}

// TetherHoldServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type TetherHoldServer_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *TetherHoldServer_Expecter) SetTrailer(mD any) *TetherHoldServer_SetTrailer_Call {
	return &TetherHoldServer_SetTrailer_Call{Call: _e.mock.On("SetTrailer", mD)}
}

func (_c *TetherHoldServer_SetTrailer_Call) Run(run func(mD metadata.MD)) *TetherHoldServer_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TetherHoldServer_SetTrailer_Call) Return() *TetherHoldServer_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *TetherHoldServer_SetTrailer_Call) RunAndReturn(run func(mD metadata.MD)) *TetherHoldServer_SetTrailer_Call {
	_c.Run(run)
	return _c
}
