// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Arm-Debug/apap-cli/clients/go/tetherproto"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc/metadata"
)

// NewTetherHoldClient creates a new instance of TetherHoldClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTetherHoldClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TetherHoldClient {
	mock := &TetherHoldClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TetherHoldClient is an autogenerated mock type for the Tether_HoldClient type
type TetherHoldClient struct {
	mock.Mock
}

type TetherHoldClient_Expecter struct {
	mock *mock.Mock
}

func (_m *TetherHoldClient) EXPECT() *TetherHoldClient_Expecter {
	return &TetherHoldClient_Expecter{mock: &_m.Mock}
}

// CloseSend provides a mock function for the type TetherHoldClient
func (_mock *TetherHoldClient) CloseSend() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseSend")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TetherHoldClient_CloseSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSend'
type TetherHoldClient_CloseSend_Call struct {
	*mock.Call
}

// CloseSend is a helper method to define mock.On call
func (_e *TetherHoldClient_Expecter) CloseSend() *TetherHoldClient_CloseSend_Call {
	return &TetherHoldClient_CloseSend_Call{Call: _e.mock.On("CloseSend")}
}

func (_c *TetherHoldClient_CloseSend_Call) Run(run func()) *TetherHoldClient_CloseSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TetherHoldClient_CloseSend_Call) Return(err error) *TetherHoldClient_CloseSend_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TetherHoldClient_CloseSend_Call) RunAndReturn(run func() error) *TetherHoldClient_CloseSend_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type TetherHoldClient
func (_mock *TetherHoldClient) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// TetherHoldClient_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type TetherHoldClient_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *TetherHoldClient_Expecter) Context() *TetherHoldClient_Context_Call {
	return &TetherHoldClient_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *TetherHoldClient_Context_Call) Run(run func()) *TetherHoldClient_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TetherHoldClient_Context_Call) Return(context1 context.Context) *TetherHoldClient_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *TetherHoldClient_Context_Call) RunAndReturn(run func() context.Context) *TetherHoldClient_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function for the type TetherHoldClient
func (_mock *TetherHoldClient) Header() (metadata.MD, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 metadata.MD
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (metadata.MD, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TetherHoldClient_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type TetherHoldClient_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *TetherHoldClient_Expecter) Header() *TetherHoldClient_Header_Call {
	return &TetherHoldClient_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *TetherHoldClient_Header_Call) Run(run func()) *TetherHoldClient_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TetherHoldClient_Header_Call) Return(mD metadata.MD, err error) *TetherHoldClient_Header_Call {
	_c.Call.Return(mD, err)
	return _c
}

func (_c *TetherHoldClient_Header_Call) RunAndReturn(run func() (metadata.MD, error)) *TetherHoldClient_Header_Call {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function for the type TetherHoldClient
func (_mock *TetherHoldClient) Recv() (*tetherproto.PulseAck, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *tetherproto.PulseAck
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*tetherproto.PulseAck, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *tetherproto.PulseAck); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tetherproto.PulseAck)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TetherHoldClient_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type TetherHoldClient_Recv_Call struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *TetherHoldClient_Expecter) Recv() *TetherHoldClient_Recv_Call {
	return &TetherHoldClient_Recv_Call{Call: _e.mock.On("Recv")}
}

func (_c *TetherHoldClient_Recv_Call) Run(run func()) *TetherHoldClient_Recv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TetherHoldClient_Recv_Call) Return(pulseAck *tetherproto.PulseAck, err error) *TetherHoldClient_Recv_Call {
	_c.Call.Return(pulseAck, err)
	return _c
}

func (_c *TetherHoldClient_Recv_Call) RunAndReturn(run func() (*tetherproto.PulseAck, error)) *TetherHoldClient_Recv_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function for the type TetherHoldClient
func (_mock *TetherHoldClient) RecvMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TetherHoldClient_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type TetherHoldClient_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *TetherHoldClient_Expecter) RecvMsg(m any) *TetherHoldClient_RecvMsg_Call {
	return &TetherHoldClient_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *TetherHoldClient_RecvMsg_Call) Run(run func(m any)) *TetherHoldClient_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TetherHoldClient_RecvMsg_Call) Return(err error) *TetherHoldClient_RecvMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TetherHoldClient_RecvMsg_Call) RunAndReturn(run func(m any) error) *TetherHoldClient_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type TetherHoldClient
func (_mock *TetherHoldClient) Send(pulseRequest *tetherproto.PulseRequest) error {
	ret := _mock.Called(pulseRequest)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*tetherproto.PulseRequest) error); ok {
		r0 = returnFunc(pulseRequest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TetherHoldClient_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type TetherHoldClient_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - pulseRequest *tetherproto.PulseRequest
func (_e *TetherHoldClient_Expecter) Send(pulseRequest any) *TetherHoldClient_Send_Call {
	return &TetherHoldClient_Send_Call{Call: _e.mock.On("Send", pulseRequest)}
}

func (_c *TetherHoldClient_Send_Call) Run(run func(pulseRequest *tetherproto.PulseRequest)) *TetherHoldClient_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *tetherproto.PulseRequest
		if args[0] != nil {
			arg0 = args[0].(*tetherproto.PulseRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TetherHoldClient_Send_Call) Return(err error) *TetherHoldClient_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TetherHoldClient_Send_Call) RunAndReturn(run func(pulseRequest *tetherproto.PulseRequest) error) *TetherHoldClient_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function for the type TetherHoldClient
func (_mock *TetherHoldClient) SendMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TetherHoldClient_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type TetherHoldClient_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *TetherHoldClient_Expecter) SendMsg(m any) *TetherHoldClient_SendMsg_Call {
	return &TetherHoldClient_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *TetherHoldClient_SendMsg_Call) Run(run func(m any)) *TetherHoldClient_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TetherHoldClient_SendMsg_Call) Return(err error) *TetherHoldClient_SendMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TetherHoldClient_SendMsg_Call) RunAndReturn(run func(m any) error) *TetherHoldClient_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Trailer provides a mock function for the type TetherHoldClient
func (_mock *TetherHoldClient) Trailer() metadata.MD {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Trailer")
	}

	var r0 metadata.MD
	if returnFunc, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}
	return r0
}

// TetherHoldClient_Trailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trailer'
type TetherHoldClient_Trailer_Call struct {
	*mock.Call
}

// Trailer is a helper method to define mock.On call
func (_e *TetherHoldClient_Expecter) Trailer() *TetherHoldClient_Trailer_Call {
	return &TetherHoldClient_Trailer_Call{Call: _e.mock.On("Trailer")}
}

func (_c *TetherHoldClient_Trailer_Call) Run(run func()) *TetherHoldClient_Trailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TetherHoldClient_Trailer_Call) Return(mD metadata.MD) *TetherHoldClient_Trailer_Call {
	_c.Call.Return(mD)
	return _c
}

func (_c *TetherHoldClient_Trailer_Call) RunAndReturn(run func() metadata.MD) *TetherHoldClient_Trailer_Call {
	_c.Call.Return(run)
	return _c
}
